### PR TITLE
Front page

### PR DESCRIPTION
**Pull request by Michaelm999**
Ok. Now I got it figured out

### CODE REVIEW

**Comment by junefish** [comment]
@seport 3rd time's a charm, here's the solid pull request for the front page

**Comment by seport** [comment]
Looking good! The only thing is that we need to rebase your branch onto master. I don't think I can do that since it's on your fork, but we can do it first thing on Wednesday night and then get this bad boy merged 🎉

**Comment by junefish** [comment]
Rebasing complete(?)

**Comment by seport** [comment]
Final changes that need to be be made:
- [ ] Add the typing jquery found in `/resources/scripts/autocomplete.js` in the old code.
- [ ] Add the bubble close button jquery found in `/resources/scripts/script.js`
- [ ] Add links to the top navigation bar (I know that these links won't go anywhere yet and will break the app when we click on them but we can add them anywhere)

**Pull request merged**
